channels:
- conda-forge
dependencies:
- python =3.11
- jupyterlab
- ipywidgets
- nglview
- pyiron =0.5.2
- pyiron_base =0.8.2
- pyiron_atomistics =0.5.2
- pyiron_continuum =0.0.9
- pyiron-data =0.0.29
- iprpy-data =2023.07.25
- lammps=2024.02.07
- sqsgenerator
- damask =3.0.0b
- openblas
- seaborn
- pip:
  - dsms-sdk==1.4.0rc11
  - data2rdf==2.0.0rc9
  - python-dotenv
